/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbo56;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Ailsa
 */
public class TampilanGUI extends javax.swing.JFrame {

    public void peringatan(String pesan) {
        JOptionPane.showMessageDialog(rootPane, pesan);
    }
    ArrayList<Dokter> dataDokter;

    private int masukkanData(Connection conn, String nama, String id_dokter, String alamat) throws SQLException {
        PreparedStatement pst = conn.prepareStatement("INSERT INTO identitas (nama, id_dokter, alamat) VALUES(?,?,?)");
        pst.setString(1, nama);
        pst.setString(2, id_dokter);
        pst.setString(3, alamat);
        return pst.executeUpdate();
    }

    private int perbaruiData(Connection conn, String nama, String id_dokter, String alamat) throws SQLException {
        PreparedStatement pst = conn.prepareStatement("UPDATE identitas SET nama=?, alamat=? WHERE id_dokter=?");
        pst.setString(1, nama);
        pst.setString(2, alamat);
        pst.setString(3, id_dokter);
        return pst.executeUpdate();
    }
    
    private int hapusData(Connection conn, String id_dokter) throws SQLException {
        PreparedStatement pst = conn.prepareStatement("DELETE FROM identitas WHERE id_dokter = ?");
        pst.setString(1, id_dokter);
        return pst.executeUpdate();
    }

    private void tampil(Connection conn) {
        dataDokter.clear();
        try {
            String sql = "select * from identitas";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Dokter data = new Dokter();
                data.setNama(String.valueOf(rs.getObject(1)));
                data.setId_dokter(String.valueOf(rs.getObject(2)));
                data.setAlamat(String.valueOf(rs.getObject(3)));
                dataDokter.add(data);
            }
            DefaultTableModel model = (DefaultTableModel) jTableDokter.getModel();
            model.setRowCount(0);
            for (Dokter data : dataDokter) {

                Object[] baris = new Object[3];
                baris[0] = data.getNama();
                baris[1] = data.getId_dokter();
                baris[2] = data.getAlamat();

                model.addRow(baris);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form TampilanGUI
     */
    public TampilanGUI() {
        try {
            dataDokter = new ArrayList<>();
            initComponents();
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Dokter", "postgres", "Chanhee98");
            tampil(conn);
        } catch (SQLException ex) {
            Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelData = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldid = new javax.swing.JTextField();
        jScrollPaneTampil = new javax.swing.JScrollPane();
        jTableDokter = new javax.swing.JTable();
        jButtonSimpan = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jLabelAlamat = new javax.swing.JLabel();
        jTextFieldAlamat = new javax.swing.JTextField();
        jButtonCetak = new javax.swing.JButton();
        jLabelNama = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelData.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(0, 51, 102));
        jLabelData.setText("DATA DOKTER");
        getContentPane().add(jLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 230, 20));

        jLabelId.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelId.setText("No ID");
        getContentPane().add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 152, 60, 30));

        jTextFieldNama.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldNama.setText(" ");
        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 300, 30));

        jTextFieldid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldid.setText(" ");
        jTextFieldid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldid, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 300, 30));

        jTableDokter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "No ID", "Alamat"
            }
        ));
        jTableDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDokterMouseClicked(evt);
            }
        });
        jScrollPaneTampil.setViewportView(jTableDokter);

        getContentPane().add(jScrollPaneTampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 407, 170));

        jButtonSimpan.setBackground(new java.awt.Color(0, 51, 102));
        jButtonSimpan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 100, 30));

        jButtonUpdate.setBackground(new java.awt.Color(0, 51, 102));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 100, -1));

        jButtonHapus.setBackground(new java.awt.Color(0, 51, 102));
        jButtonHapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonHapus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 100, 30));

        jLabelAlamat.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelAlamat.setText("Alamat");
        getContentPane().add(jLabelAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 67, 30));

        jTextFieldAlamat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldAlamat.setText(" ");
        jTextFieldAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 300, 30));

        jButtonCetak.setBackground(new java.awt.Color(0, 51, 102));
        jButtonCetak.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCetak.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCetak.setText("Cetak");
        jButtonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCetakActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 134, 40));

        jLabelNama.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelNama.setText("Nama");
        getContentPane().add(jLabelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 67, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ailsa\\Downloads\\Keren.jpeg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 940));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldidActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        String nama = jTextFieldNama.getText().trim();
        String id_dokter = jTextFieldid.getText();
        String alamat = jTextFieldAlamat.getText();

        if (!nama.isEmpty() && !id_dokter.isEmpty() && !alamat.isEmpty()) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Dokter", "postgres", "Chanhee98");
                int k = masukkanData(conn, nama, id_dokter, alamat);
                if (k > 0) {
                    tampil(conn);
                    this.peringatan("Simpan Berhasil");
                } else {
                    this.peringatan("Simpan Gagal");
                }
            } catch (SQLException ex) {
                Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.peringatan("Input Data Mahasiswa Gagal");
        }

        jTextFieldNama.setText("");
        jTextFieldid.setText("");
        jTextFieldAlamat.setText("");

    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        String nama = jTextFieldNama.getText().trim();
        String id_dokter = jTextFieldid.getText();
        String alamat = jTextFieldAlamat.getText();

        if (!nama.isEmpty() && !id_dokter.isEmpty() && !alamat.isEmpty()) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Dokter", "postgres", "Chanhee98");
                int k = perbaruiData(conn, nama, id_dokter, alamat);
                if (k > 0) {
                    tampil(conn);
                    this.peringatan("Update Berhasil");
                } else {
                    this.peringatan("Update Gagal");
                }
            } catch (SQLException ex) {
                Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.peringatan("Input Data Mahasiswa Gagal");
        }

        jTextFieldNama.setText("");
        jTextFieldid.setText("");
        jTextFieldAlamat.setText("");

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        String id_dokter = jTextFieldid.getText().trim();
       
        if (!id_dokter.isEmpty()) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Dokter", "postgres", "Chanhee98");
                int k = hapusData(conn, id_dokter);
                if (k > 0) {
                    tampil(conn);
                    this.peringatan("Hapus Berhasil");
                } else {
                    this.peringatan("Hapus Gagal");
                }
            } catch (SQLException ex) {
                Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.peringatan("Input Data Mahasiswa Gagal");
        }

        jTextFieldid.setText("");
        jTextFieldNama.setText("");
        jTextFieldAlamat.setText("");

    }//GEN-LAST:event_jButtonHapusActionPerformed
    
    private void jTextFieldAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlamatActionPerformed

    private void jTableDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDokterMouseClicked
        // TODO add your handling code here:
        int baris = jTableDokter.rowAtPoint(evt.getPoint());

        String Nama = jTableDokter.getValueAt(baris, 0).toString();
        jTextFieldNama.setText(Nama);

        String Id_dokter = jTableDokter.getValueAt(baris, 1).toString();
        jTextFieldid.setText(Id_dokter);

        String Alamat = jTableDokter.getValueAt(baris, 2).toString();
        jTextFieldAlamat.setText(Alamat);

    }//GEN-LAST:event_jTableDokterMouseClicked

    private void jButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCetakActionPerformed
        // TODO add your handling code here:
                try {
            // TODO add your handling code here:
           Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Dokter", "postgres", "Chanhee98");

            //File jasperFile = new File("src/pbopertemuan6/mahasiswa.jasper");
            // JasperPrint jp = JasperFillManager.fillReport(jasperFile.getPath(), null, conn);
            String jrxmlFile = new String("src/pbo5/Dokter.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex) {
            Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);}
    }//GEN-LAST:event_jButtonCetakActionPerformed

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanGUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCetak;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAlamat;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JScrollPane jScrollPaneTampil;
    private javax.swing.JTable jTableDokter;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldid;
    // End of variables declaration//GEN-END:variables
}
